import React from 'react';
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import { StyledComponentsRegistry } from "@/lib/registry";

import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight:['400', '500', '700', '200'],
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
